### ISSUE TITLE
cannot connect to Nexus - unknown namespace

### ISSUE THREAD

**Issue by anubisg1** [cisco-ie/anx#10]
When connecting to Nexus 9000 running NX-OS 9.2.2 i fail connection with the following error:

Failed to retrieve schemas: unknown-namespace: Namespace="urn:ietf:params:xml:yang:ietf-netconf-monitoring"

docker logs show this trace

```
nx_1  | com.cisco.stbarth.netconf.anc.NetconfException$RPCException: unknown-namespace: Namespace="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"
anx_1  |        at com.cisco.stbarth.netconf.anc.NetconfSession.call(NetconfSession.java:188)
anx_1  |        at com.cisco.stbarth.netconf.anc.NetconfSession.get(NetconfSession.java:195)
anx_1  |        at com.cisco.stbarth.netconf.anc.NetconfSession.get(NetconfSession.java:263)
anx_1  |        at com.cisco.stbarth.netconf.anx.NetconfYangParser.getAvailableSchemas(NetconfYangParser.java:83)
anx_1  |        at com.cisco.stbarth.netconf.anx.RetrieverView.lambda$new$5ee12248$1(RetrieverView.java:237)
anx_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
anx_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
anx_1  |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
anx_1  |        at java.lang.reflect.Method.invoke(Method.java:498)
anx_1  |        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
anx_1  |        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
anx_1  |        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
anx_1  |        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
anx_1  |        at com.vaadin.ui.Button.fireClick(Button.java:384)
anx_1  |        at com.vaadin.ui.Button$1.click(Button.java:57)
anx_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
anx_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
anx_1  |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
anx_1  |        at java.lang.reflect.Method.invoke(Method.java:498)
anx_1  |        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
anx_1  |        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
anx_1  |        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
anx_1  |        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
anx_1  |        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
anx_1  |        at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:148)
anx_1  |        at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:248)
anx_1  |        at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:534)
anx_1  |        at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
anx_1  |        at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
anx_1  |        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
anx_1  |        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
anx_1  |        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
anx_1  |        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
anx_1  |        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
anx_1  |        at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
anx_1  |        at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
anx_1  |        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
anx_1  |        at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448)
anx_1  |        at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272)
anx_1  |        at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269)
anx_1  |        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395)
anx_1  |        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
anx_1  |        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
anx_1  |        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
anx_1  |        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
anx_1  |        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
anx_1  |        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
anx_1  |        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
anx_1  |        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
anx_1  |        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
anx_1  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
anx_1  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
anx_1  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
anx_1  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
anx_1  |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
anx_1  |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
anx_1  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
anx_1  |        at java.lang.Thread.run(Thread.java:748)
```

**Comment by remingtonc** [comment]
@sbyx Is this due to https://datatracker.ietf.org/doc/rfc6022/ not being present on NX-OS?
https://github.com/YangModels/yang/tree/master/vendor/cisco/nx/9.2-2

**Comment by sbyx** [comment]
Correct, get-schema needs to be implemented for ANX to work.
________________________________

**Comment by anubisg1** [comment]
i see this was closed. can i assume this was fixed? 

thank you

**Comment by sbyx** [comment]
Not aware that it has been fixed as of now. However this issue is not related to this repo and rather is a missing feature on NX-OS and I do not see a work-around here that would be possible to implement.

**Comment by anubisg1** [comment]
ok thank you. :( is a shame, this tool would have been very useful..

all right, NX-OS not supported then. thanks
