### ISSUE TITLE
IOS-XE netconf-yang feature candidate-datastore

### ISSUE THREAD

**Issue by tylersiemers** [cisco-ie/anx#15]
Is it a requirement to have the following config on an XE router?

netconf-yang feature candidate-datastore

Model: ASR920
Version: 16.12.1

Without it configured ANX won't connect to the router and gives the following error.

![Screen Shot 2019-10-14 at 1 16 06 PM](https://user-images.githubusercontent.com/34378914/66773574-ed8c4f00-ee84-11e9-9653-a241a3feea78.png)

After adding that line of config it connects just fine.

**Comment by sbyx** [comment]
I believe "netconf-yang" itself should suffice. Are you seeing any issues with just that?

**Comment by tylersiemers** [comment]
Yes. With just netconf-yang the above error message. 

docker logs without 'netconf-yang feature candidate-datastore' command:

`[Fatal Error] :1:1: Premature end of file.
com.cisco.stbarth.netconf.anc.NetconfException$ProtocolException: com.cisco.stbarth.netconf.anc.XMLElement$XMLException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.cisco.stbarth.netconf.anc.NetconfSession.receive(NetconfSession.java:119)
        at com.cisco.stbarth.netconf.anc.NetconfSession.request(NetconfSession.java:104)
        at com.cisco.stbarth.netconf.anc.NetconfSession.hello(NetconfSession.java:58)
        at com.cisco.stbarth.netconf.anc.NetconfSSHClient.createSession(NetconfSSHClient.java:132)
        at com.cisco.stbarth.netconf.anx.RetrieverView.lambda$new$5ee12248$1(RetrieverView.java:236)
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
        at com.vaadin.ui.Button.fireClick(Button.java:384)
        at com.vaadin.ui.Button$1.click(Button.java:57)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
        at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:148)
        at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:248)
        at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:534)
        at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
        at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
        at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
        at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448)
        at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272)
        at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.cisco.stbarth.netconf.anc.XMLElement$XMLException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.cisco.stbarth.netconf.anc.XMLElement.<init>(XMLElement.java:77)
        at com.cisco.stbarth.netconf.anc.NetconfSession.receive(NetconfSession.java:117)
        ... 55 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at com.cisco.stbarth.netconf.anc.XMLElement.<init>(XMLElement.java:75)
        ... 56 more`

**Comment by timesnewmen** [comment]
same issue here. CSR1000V, Version 16.9.4. Actually, I can not login, always shown this error. Also tried some other versions, not sure what is the issue.

**Comment by nickrusso42518** [comment]
Not seeing issues on 16.12 or 17.01. I *did* see this error initially, but I just waited about 30 seconds after enabling `netconf-yang` before it started working.

**Comment by sbyx** [comment]
Thanks for the note. Closing this then.
